### ISSUE TITLE
Поддержка брокера ВТБ. Часть 2

### ISSUE THREAD

**Issue by vananiev** [spacious-team/investbook#120]
В части 1 (gh-33) реализован парсер отчетов ВТБ. Однако за неимением примера отчета брокера парсер не выполняет извлечение информации о:
1. Выплате купонов, амортизации и погашения облигаций.
1. Экспирации фьючерсов и опционов.
1. Транзакциях на валютном рынке.

Нужен пример отчета с указанной информацией.

**Comment by vananiev** [comment]
Ожидаю пример отчета от пользователей по событиям описанным в первом комментарии.

**Comment by vananiev** [comment]
Ожидаю пример отчета от пользователей по событиям описанным в первом комментарии.

**Comment by pausto** [comment]
> Ожидаю пример отчета от пользователей по событиям описанным в первом комментарии.

Подскажите, откуда должны выгружаться отчеты(Quik, сайт брокера), в каком формате(HTML, XLS, XML). 
Где можно пример отчета посмотреть для понимания как он должен выглядеть?

**Comment by vananiev** [comment]
3. Экспирация фьючерсов протестирована. Работает корректно на версии 2020.11 (gh-33)

**Comment by vananiev** [comment]
Осталось
1. События погашения облигаций.
1. Экспирации опционов.
1. Транзакциях на валютном рынке.
Пример по п. 3 имеется.

**Comment by vananiev** [comment]
Осталось сделать
1. События погашения облигаций.
1. Экспирации опционов.

**Comment by vananiev** [comment]
Закрываю, при необходимости переоткрыть.

**Comment by vananiev** [comment]
Пример отчета по Событим погашения облигаций получен, корректная обработка реализована с 2020.12.1
