### ISSUE TITLE
Поправить стилистику, орфографию и грамматику описания файла выгрузки

### ISSUE THREAD

**Issue by vananiev** [spacious-team/investbook#123]
Необходимо вычитать описание выгрузки, расположенное в папке [src/main/asciidoc/](https://github.com/spacious-team/investbook/tree/develop/src/main/asciidoc), и выполнить правки при необходимости. Цель - сделать текст понятнее и читабельнее.

**Comment by Alex5545** [comment]
9 строка захвачена, чтобы полное предложение вроде получилось. Это неинформативно, как я понял было. Точнее лишнее.

**Comment by vananiev** [comment]
Осталось вычитать файл `src/main/asciidoc/derivatives-market-profit.adoc`
