### ISSUE TITLE
Перевод README на английский

### ISSUE THREAD

**Issue by vananiev** [spacious-team/investbook#265]

**Comment by vimalJD** [comment]
### Is this project is ongoing? Let me know further (DOCS) to contribute on it as "good first issue".

**Comment by vimalJD** [comment]
Is this project ongoing? Let me know further (DOCS) to contribute to it as a "good first issue"?

**Comment by Sheventon** [comment]
Привет, @vananiev! Я могу заняться данным issue

**Comment by vananiev** [comment]
Привет, @Sheventon! Отлично, задачей сейчас никто не занимается! Готов принять от вас PR.

**Comment by Sheventon** [comment]
@vananiev, я сделал PR, но не смог добавить ревьюера, прикрепляю ссылку сюда: https://github.com/spacious-team/investbook/pull/590

**Comment by vananiev** [comment]
![ru](https://github.com/spacious-team/investbook/assets/11336712/14847ff5-827e-4d0f-a4e9-882cb0d1397c)
![en](https://github.com/spacious-team/investbook/assets/11336712/7b16c124-5230-403e-8df9-7652132e76dd)
