### ISSUE TITLE
ВТБ. Рекомендации по доработке

### ISSUE THREAD

**Issue by vananiev** [spacious-team/investbook#287]
Получен запрос с примерами отчетов на e-mail.

> бегло глянул первый отчет, "детальная информация" и вижу следующее:
> 1) "портфель RUB" - в строке "Остаток денежных средств, rub" (последняя строка) все поля пустые. на счете, естественно, есть остаток. Наводит на мысль, что цифры не рассчитываются на основе сделок и прочего, а берутся видимо из отчета. Значит, по прежнему не все парсится в отчетах ВТБ. При этом в логе нет никаких сообщений на эту тему.
> 2) текущая цена бумаг отображается некорректно, хотя я загрузил все котировки мосбиржи. Пример: котировка ГМК Норникель по факту 26646 (и на moex.com/ru/data тоже самое), однако в столбце "текущая цена" отображается 26100
> 3) графики не рисуются
> 4) "... (фондовый) RUB" - заполнены только столбцы: бумага, дата открытия, количество, дата закрытия. в остальных стоит прочерк (-). нет даже цены. Кстати, отображаются только покупки, и совсем нет продаж (в столбце "количество" только положительные значения).
>  
> все что тут написано, можно увидеть после загрузки приложенных ТРЕХ брокерских отчетов ВТБ и относится только к отчету "детальная информация".
> п.4 "... (фондовый) RUB" -  это вкладка в полученном отчете "детальная информация": номер_счета + (фондовый) RUB. Я не знаю, что там вообще должно быть :), но отображаются только покупки, продаж нет (в документации написано, что продажи идут как отрицательные числа в столбце "количество")
>  
> По моему мнению, основная проблема - это загрузка отчета "без ошибок и предупреждений", хотя явно не все удалось распарсить. При таком подходе теряется целостность данных и создается неверное впечатление о том, что все в порядке. Могу тока посоветовать не загружать проблемный отчет и сигнализировать об ошибке.

**Comment by vananiev** [comment]
1. Решено в gh-293 (2021.4.2). Прогрузил ваши отчеты, проблем сейчас нет. Причина - брокер поменял формат отчета. Если обратите внимание на таблицу "Отчет об остатках денежных средств" в старых и новых отчетах, то в новых пропало слово "площадка" в заголовке. Сейчас оба формата учитываются.
2. Я думаю вопрос закрыли в [теме](https://www.banki.ru/forum/?PAGE_NAME=message&FID=21&TID=380178&MID=8600476#message8600476) на banki.ru. Тезисно: котировки корректны, если ожидаете видеть цену закрытия. Чтобы в отчете Investbook обновлялись котировки, нужно либо загрузить свежий отчет, либо стянуть еще раз с МосБиржи котировки через раздел Форм. Investbook в интернет самостоятельно не лезет (такова просьба пользователей приложения). Если вы обновляли котировки 4 мая с МосБиржи и собираете отчет в час ночи 6 мая, нужно еще раз подтянуть котировки с сайта МосБиржи, в отчете отобразятся цены закрытия торгов (18:45) 5 мая. Без этого будут отображаться ранее полученные котировки (от 4 мая).
3. вы предоставили мне 3 отчета для примера. 1 отчет - 1 точка на графике роста активов, т.к. стоимости активов берется из отчета брокера, а не расчитывается ежедневно по интернет-данным (Investbook - оффлайн приложение, безопасное для инвесторов). На версии 2021.4.2 по вашему портфелю рисуются такие графики
![2021-05-15_23-57-53](https://user-images.githubusercontent.com/11336712/118378007-6a3f5c00-b5d9-11eb-833a-7a331d023a81.png)
![2021-05-16_00-01-47](https://user-images.githubusercontent.com/11336712/118378091-efc30c00-b5d9-11eb-83de-a6e07ecb92c8.png)
4. По ващим отчетам на версии 2021.4.2 отображается все параметры сделок и цены в т.ч. Продажи по методу FIFO сопоставляются с покупками. Обратите внимание на колонку "Дата закрытия позиции" - это дата, в которую вы продали указанное количество бумаг. Это позволяет рассчитать налог со сделки, который ваставит вам в конце года брокер, который использует тот же метод FIFO для его расчета, что и Investbook
![2021-05-16_00-03-49](https://user-images.githubusercontent.com/11336712/118378186-9ad3c580-b5da-11eb-8512-c94642b04169.png)

**Comment by vlalykin** [comment]
Спасибо за исправления. не проверял еще :)
**по п .2 Вы пишите:**

> Если вы обновляли котировки 4 мая с МосБиржи и собираете отчет в час ночи 6 мая, нужно еще раз подтянуть котировки с сайта МосБиржи, в отчете отобразятся цены закрытия торгов (18:45) 5 мая. Без этого будут отображаться ранее полученные котировки (от 4 мая).

я загружал котировки непосредственно перед построением отчета (как раз ночью 6 мая), даже два раза, о чем в логе (см.  banki.ru) имеются подnверждающие записи.


**по п.5** мне понятна Ваша аргументация:

> если отказывать загружать такие отчеты, то приложением быстро станет невозможно пользоваться

 но я считаю, что нужно понимать, какие данные достоверны, а какие - нет. Иначе невозможно доверять приложению. 
Чтобы обнаружить ошибку в данных, нужно где то иметь гарантированно правильные данные. И каждый раз вручную проверять. В чем тогда смысл ? вместо автоматизации рутинных действий получаем постоянные сверки. Если в отчете что-то изменилось, то нужно об этом сигнализировать, чтобы пользователь хотя бы понимал, на каких вкладках можно ожидать расхождения с действительностью. Если этого не будет, то ошибку можно не замечать долго, даже годами, пока кто-то случайно не заметит.

**Comment by vananiev** [comment]
Я вел речь не об ошибках в итоговом отчете. То, что загрузилось, должно отображаться корректно. Я говорил об изменении формата очета брокера. При этом ошибки парсинга таких отчетов не приводят к невозможности загрузки отчета в целом, ведется запись предупреждений в лог, что может парсится.

**Comment by vlalykin** [comment]
> Но если формат очета брокера изменился, то ошибка парсинга таких отчетов не приводит к невозможности загрузки отчета в целом, ведется запись предупреждений в лог, но информация, которая может быть получена из отчета брокера, извлекается.
- в моем случае в лог ничего не выводилось. 
- Я не знаю точно, как все устроено, но предположим что в отчете брокера есть "3", есть "2", и есть "5" как сумма "3" + "2". Допустим изменился формат отчета, и удалось распарсить только "2" и "3", а "5" - не получилось. Далее на основе этих данных что-то считается (доходность, налоги или что-то еще), или же график не правильно показывает, или еще что-то (я не знаю что, просто предполагаю). Неправильно потому, что не извлекли из отчета "5". Я говорю об этом. Как понять, что есть ошибка ? А если из-за этого налоги неправильно посчитаются ? это уже критично. я об этом пишу. Делайте, конечно, как хотите. Просто мое "имхо".

**Comment by vananiev** [comment]
Если будет ситуация неконсистентности данных, которую вы описали, то будет ошибка в логе. Если у вас не было ошибки в логах, значит не будет ошибки при подсчетах. Если у вас, например возможно, не распарсились денежные остатки (сужу по последним изменениям отчета ВТБ), то ошибки в расчетах не будет. Денежные остатки в Investbook используются только для отображения, для информации и никак не участвуют в подсчете чего либо.
