### ISSUE TITLE
Error in your SQL syntax при первом запуске проекта

### ISSUE THREAD

**Issue by rint1k** [spacious-team/investbook#347]
**Описание ошибки**
Migration V2020_13_0_0.sql failed
---------------------------------
SQL State  : 42000
Error Code : 1064
Message    : You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF EXISTS `isin` `security` varchar(64) NOT NULL
        COMMENT 'Инструм' at line 25
Location   : db/migration/mysql/V2020_13_0_0.sql 
Line       : 24
Statement  : /*

**Последовательность действий для воспроизведения**
Шаги по воспроизведению ошибки:
1. Запустить проект (бд пустая, никаких таблиц еще не создано)
2. Ругается на IF EXISTS, IF NOT EXISTS, DROP FOREIGN KEY, DROP KEY

**Окружение:**
 - macOS Big Sur 11.1

**Дополнительный контекст**
Возможно проблема в версии MySQL (у меня стоит 8.0.25)

**Comment by vananiev** [comment]
В режиме разработки по-умолчанию используется MariaDB. Можно переключиться на H2 см конфиг https://github.com/spacious-team/investbook/blob/develop/src/main/resources/application-dev.properties

MySql не подходит, проект open source, поэтому писалось все под MariaDB. Попробуйте, пожалуйста, установить с помощью инструкции https://mariadb.com/kb/en/installing-mariadb-on-macos-using-homebrew/

Какую бы СУБД не продолжили использовать, пожалуйста, отпишитесь о результатах для других.

**Comment by rint1k** [comment]
Перешел на h2, проект запускается без ошибок, спасибо)

**Comment by rint1k** [comment]
Установил Mariadb, все равно ошибка выскакивает

**Comment by vananiev** [comment]
Какая версия MariaDB ?

**Comment by rint1k** [comment]
Distrib 10.6.3-MariaDB

**Comment by vananiev** [comment]
Странно, у меня работало на 10.4.12 (cборка win32). Выше у тебя лог по MySQL. Приведи пожалуйста ошибку MariaDB, желательно весь стэк-трейс.

**Comment by vananiev** [comment]
Лога от вас не получил. Выставил H2 по умолчанию. Ошибки на MariaDB быть не должно, пробуйте удалить БД `portfolio`  и запуститься заново. Если ошибка сохраняется, приложите лог и переоткройте заявку.
