### ISSUE TITLE
ВТБ. Поддержка сплитов

### ISSUE THREAD

**Issue by aakatov** [spacious-team/investbook#352]
**Связан ли ваш запрос новой функциональности с проблемой? Пожалуйста, опишите.**
Да. После сплитов акций и ETF (например, FXDE и VTBE) приложение неверно показывает кол-во в "Куплено" и, как следствие, прибыль и доходность.

**Опишите желаемое решение**
Необходимо парсить в отчете раздел "Движение ценных бумаг" события "Зачисление ЦБ" и "Списание ЦБ" и отображать корректное кол-во бумаг в отчете.

**Comment by vananiev** [comment]
Отчет какого брокера загружаете? Или может руками забиваете данные через Формы?

**Comment by aakatov** [comment]
отчет ВТБ, sorry

**Comment by vananiev** [comment]
Я посмотрю на своих примерах, можете ли предоставить пример проблемного отчета? Личную информацию можно удалить в телеграме связаться со мной можно в группе investbook_support (файл туда не выкладывать).

**Comment by aakatov** [comment]
@vananiev прошу прощения за задержку. Сплит ETF Finex с первого взгляда работает. Но сплит Apple в 2020 году нет.

![изображение](https://user-images.githubusercontent.com/6240291/147382461-41098e49-4f79-410c-b28e-255f12b48d42.png)

Была 1 акция до сплита. Потом купил еще 5 акций после сплита. В итоге должно было получиться 1 * 4 + 5 = 9, но приложение начисленные 4 акции при сплите не видит.

**Comment by aakatov** [comment]
Еще раз изучил сплит Finex, есть небольшая ошибка. Похоже, приложение не понимает событие "Списание ЦБ", отображаемое кол-во = кол-во до сплита + кол-во после сплита.

**Comment by vananiev** [comment]
@ aakatov, исправлено на примере вашего отчета в gh-395. Выйдет в следующем релизе, просто перезагрузите отчет, данные не задвоятся, а сплит начнет отображаться правильно. Спасибо, что помогли примером :-)
