### ISSUE TITLE
Текущая стоимость открытых позиций

### ISSUE THREAD

**Issue by MBogda** [spacious-team/investbook#37]
v 2020.4
Сейчас не отображается текущая стоимость открытых (купленных, но не проданных) позиций, имеется только общая ликвидная стоимость портфеля на вкладке "Доходность".
Хочется иметь числа по текущей ликвидной стоимости отдельных бумаг (получать их из последнего брокерского отчёта), а именно: текущая стоимость, текущая прибыль (было бы шикарно видеть её сразу с учётом будущей комиссии на продажу, но это скорее всего отдельный фичреквест) в рублях и в процентах, а также доля данной ценной бумаги во всём портфеле, и доля прибыли данной ценной бумаги в прибыли портфеля.

Т.к. на текущей вкладке акций одни и те же акции, купленные в разные даты, записаны разными строками, возможно предлагаемый функционал надо реализовывать на отдельной вкладке, где одной ценной бумаге будет соответствовать одна строка. Там же можно отображать остаток свободных денежных средств.

Данный функционал будет полезен для анализа текущего состояния портфеля, т.к. в большинстве случаев у участников рынка имеются незакрытые позиции, по которым хочется видеть актуальную информацию.

**Comment by MBogda** [comment]
@vananiev привет!
Я ещё не разбирался в структуре кода проекта, поэтому хотелось бы твоей оценки - сколько примерно времени может занять данная фича в самом простом виде? Если реально сделать за 1-2 дня, то могу сам взяться за реализацию.

**Comment by vananiev** [comment]
Я думал над этой фичей. Если смотреть с точки зрения доходности, валить купленные от разных дат и цен покупки в одну строчку мне кажется нет смысла, потому что посчитаем среднюю доходность в виде средней температуры по больнице. Важно понимать, что в ту дату акция была куплена дорога, а в другую правильно, сделать выводы по графику. Я думал сделать так: на странице транзакций для открытых позиций серым цветом подставлять текущую рыночную цену и комиссию закрытия позиции и считать доходность, таким образом можно будет тут же закрыть позицию, если доходность устраивает. Но эта фича сразу завяжет приложение на подключении к интернету. А именно оффлайн работа является фишкой.

То что ты пишешь в принципе удобно просто для оценки того, какое соотношение бумаг в портфеле, есть ли перекос в одного эмитетна (какой при этом риск) и сколько в денежном выражении стоят акции сейчас.  Последняя информация совсем бесполезна, какой вывод по ней можно сделать кроме удовольствия от вида этой цифры :-)

Считаешь достаточно текущее соотношение цен бумаг в портфеле? Приблизительно так
| Бумага | Цена | Количество | Стоимость | % стоимости портфеля | Валюта | Остаток
|---|---|---|---|---|---|---|
| Итого | | xxx| yyy| |
| A | 111 | 2 | 222 | 11% | RUB | 1000
| B | 333 | 3 | 999 | 44,5% | USD | 120

Но эта таблица скопирует QUIK 

p.s. фичу можно сделать за 2-4 дня. Информация о стоимости бумаг заносить в таблицу security, завести там колонку `price DECIMAL(8,2) UNSIGNED NULL DEFAULT NULL COMMENT 'рыночная цена одной ЦБ'` для последней известной цены 1 ЦБ (не лота), надо понимать эта цена будет почти всегда устаревшей. Поэтому может сделать потом сетевую версию ПО с получением текущих котировок.

**Comment by vananiev** [comment]
Можно посмотреть в сторону [API](https://iss.moex.com/iss/reference/) московской биржи.
Но это точно должно быть выключено из коробки, чтобы не пугать пользователей необходимостью онлайн.

**Comment by vananiev** [comment]
Можно цену ЦБ брать из отчета.

**Comment by vananiev** [comment]
Из запрошенных в первом сообщении колонок:

1. текущая стоимость
1. текущая прибыль (было бы шикарно видеть её сразу с учётом будущей комиссии на продажу, но это скорее всего отдельный фичреквест) в рублях
1. текущая прибыль в процентах
1. доля прибыли данной ценной бумаги в прибыли портфеля
1. остаток свободных денежных средств
1. доля данной ценной бумаги во всём портфеле

Последний пункт сделан по балансовой стоимости. Пункты 1-4 сделаю, однако надо понимать, что прибыль будет не чистая (будут вычтены комиссии, но не вычтены ожидающиеся налоги, для вычета которых нужно использовать принцип FIFO, а для его использования учетной единицей должны быть транзакции, а не агрегированния информация по ЦБ). По п. 5 (остатку ДС) тоже есть информация в БД, посмотрю, что смогу сделать.

**Comment by vananiev** [comment]
Все пункты, кроме 3 сделал. Пункт 3 вынес отдельной задачей.

По п. 5 остаток ДС отображается, но участвует в доле портфеля только когда выгрузка делается с даты открытия счета, иначе для выгрузки по произвольному периоду по ЦБ отображается изменения в доле портфеля и их некорректно перемешивать с остатком ДС (а не его изменением за период).
По п. 6 долю сделал в двух видах: доля вложений в ценную бумагу и текущая доля ЦБ в портфеле.

**Comment by vananiev** [comment]
Чтобы начали отображаться значения в колонках "Цена" и "Доля в портфеле, %" нужно прогрузить хотя бы один отчет на версии 2020.10. Из отчета будут взяты текущие цены бумаг.
