### ISSUE TITLE
Обновить реализацию сервиса выгрузки курсов валют ЦБ РФ

### ISSUE THREAD

**Issue by vananiev** [spacious-team/investbook#373]
Использовать информацию из [технической документации](http://www.cbr.ru/development/sxml/#highlight=%D0%BA%D0%BE%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%BA%D0%B8%7C%D0%B2%D0%B0%D0%BB%D1%8E%D1%82) с сайта ЦБ.

> Пример получения динамики котировок доллара США:
> http://www.cbr.ru/scripts/XML_dynamic.asp?date_req1=02/03/2001&date_req2=14/03/2001&VAL_NM_RQ=R01235
>     date_req1 — date_req2 =   Date range
>     VAL_NM_RQ — unique code

> Справочник по кодам валют: http://www.cbr.ru/scripts/XML_val.asp?d=0

**Comment by vananiev** [comment]
Текущий способ выгрузки заработал после фикса fd88c8f, приоритет понижаю.

**Comment by dimio** [comment]
На данный момент обновление курсов валют падает с `403 Forbidden` из-за включённой на cbr.ru защиты от DDoS.
Что, вероятно, может повлиять на приоритет тикета.

**Comment by dimio** [comment]
Мне - не срочно. Я, как раз, хотел этот тикет взять, но решил обратить внимание на его приоритет. Т.к. по наличию свободного времени сейчас - не считаю себя вправе забирать критичные задачи.

**Comment by vananiev** [comment]
Сейчас обновление не  падает, видимо, ЦБ починили.

**Comment by dimio** [comment]
> Но все равно сделал получение курсов через xml, работает быстрее.

Мне для самообразования :)  - а почему не использовали спринговый WebServiceTemplate? И схему в src поместили, а не в ресурсы?

**Comment by vananiev** [comment]
> почему не использовали спринговый WebServiceTemplate?

Rest работаю, не знал, почитал, можно было и спринговым сервисом сделать. Если доработаете и будет проще, будет хорошо.

> И схему в src поместили, а не в ресурсы?

В место по умолчанию для плагина поместил, лишняя кастомизация - плохо. И в jar схема подкладывать, она компилится на этапе сборки.
