### ISSUE TITLE
Неверная цена покупки после сплита

### ISSUE THREAD

**Issue by aakatov** [spacious-team/investbook#419]
Для ВТБ в аналитике в столбце усредненная цена (покупки) отображается неверная цифра для позиций после сплита по инструментам:
VTBE ETF
FXDE ETF
FXUS ETF

**Comment by vananiev** [comment]
Можете прислать пример отчета в telegram?

**Comment by vananiev** [comment]
Пример файла получен. Ожидаемые усредненные цены:
FXUS 46.54
VTBE 98.06 
FXDE 25.006

**Comment by vananiev** [comment]
Причина понятна. Есть алгоритм, которые не позволяет учитывать при расчете средней цены бумаги, выведенные со счета депо. Например, куплены 5 бумаг, затрачено всего 500 рублей (для простоты 5х100), средняя - 100 рублей. Если вывести одну бумагу со счета, то останется 4 бумаги и 500 рублей затрат на покупку. Действующий алгоритм исключает цену выведенной бумаги (FIFO) из объема инвестиций, поэтому средняя будет не 500/4 = 125 руб, а попрежмему 400/ 400 = 100 рублей.

Сплит - это 2 операции: списание и зачисление бумаг. Т.к. действующий алгоритм сохраняет среднюю, то поэтому средняя не уменьшается кратно коэффициенту сплита.

Алгоритм будет доработан следующим образом. Будет делаться предсказание является списание бумаг частью сплита, и если так, то среднюю вычислять с его учетом (аналогично для зачисления). Алгоритм будет скать парные операции списание-зачисление, проведенные в течении дня - эти операции будут считаться сплитом.
