### ISSUE TITLE
Открывать анимированное изображение на время старта приложения

### ISSUE THREAD

**Issue by vananiev** [spacious-team/investbook#578]
Сейчас приложение полностью стартует, а после этого открывается главная страница. Это может занимать какое-то время, и пользователь не понимает запустилось ли приложение.

Нужно сразу стартовать браузер и в процессе запуска отображать анимированное (желательное) изображение. Эта страница должна через javascript опрашивать готовность приложения и делать редирект после ее готовности.

**Comment by DanielVsh** [comment]
Hi @vananiev, I would be happy to contribute. Would you mind?

**Comment by vananiev** [comment]
It would be great. You are welcome 👍

**Comment by DanielVsh** [comment]
Hi @vananiev, I made some changes (PR is open), could you please share your thoughts. Thanks

**Comment by vananiev** [comment]
@DanielVsh, good job. I left some comments on the code.
