### ISSUE TITLE
Добавить в формах, в таблицах событий, возможность фильтрации нужных строк по колонке "Событие"

### ISSUE THREAD

**Issue by gurusms** [spacious-team/investbook#583]
Брокер Сбербанк.
В файлах событий и файлах движения ДС от брокера есть несогласование по соответствию поля "Код инструмента". В итоге события погашения бумаги не связываются с необходимой бумагой при импорте.
Для того чтобы это исправить, необходимо привязать в событии погашения необходимый инструмент вручную.
Для удобства этой процедуры было бы удобно иметь возможность фильтрации событий. И выводить в таблице только нужные из сущетвтвующих событий, для их корректировки.

**Comment by vananiev** [comment]
Добавлен фильтр по типу операций
![изображение](https://github.com/user-attachments/assets/d03d75ab-2f79-4a7a-8615-2a9f341ca575)
