### ISSUE TITLE
Возможность включения подсветки строк в таблице событий, где отсутствует привязка к инструменту.

### ISSUE THREAD

**Issue by gurusms** [spacious-team/investbook#584]
Брокер Сбербанк.
В файлах событий и файлах движения ДС от брокера есть несогласование по соответствию поля "Код инструмента". В итоге события погашения бумаги не связываются с необходимой бумагой при импорте.
Для того чтобы это исправить, необходимо привязать в событии погашения необходимый инструмент вручную.
Для удобства этой процедуры было бы удобно иметь возможность включения подсветки строк в таблице событий, где отсутствует привязка к инструменту, для дальнейшей корректировки.

**Comment by vananiev** [comment]
Relates #583

**Comment by vananiev** [comment]
Справа от колонки "Описание" для событий, по которым можно указать ценную бумагу, добавлена пиктограмма
![изображение](https://github.com/user-attachments/assets/c43699d3-be51-441e-bd27-e4e4c76ab870)
Если нажать по ней, то открывается окно редактирования для добавления наименования ценной бумаги.
